from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest


def _load_script_module(name: str, relative_path: str) -> ModuleType:
    path = Path(relative_path)
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise AssertionError(f"failed to load script module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def test_generate_protocol_types_exposes_named_stage_commands() -> None:
    module = _load_script_module("generate_protocol_types", "scripts/generate_protocol_types.py")

    schema_command = module.build_schema_export_command(
        codex_bin="/tmp/codex",
        schema_dir=Path("/tmp/schema-dir"),
        experimental=True,
    )
    codegen_command = module.build_datamodel_codegen_command(
        schema_path=Path("/tmp/schema-dir/codex_app_server_protocol.schemas.json"),
        output_path=Path("/tmp/types.py"),
    )

    assert schema_command == [
        "/tmp/codex",
        "app-server",
        "generate-json-schema",
        "--out",
        "/tmp/schema-dir",
        "--experimental",
    ]
    assert codegen_command == [
        "uvx",
        "--from",
        "datamodel-code-generator",
        "datamodel-codegen",
        "--input",
        "/tmp/schema-dir/codex_app_server_protocol.schemas.json",
        "--input-file-type",
        "jsonschema",
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        "--use-annotated",
        "--use-title-as-name",
        "--enum-field-as-literal",
        "all",
        "--output",
        "/tmp/types.py",
    ]


def test_generate_protocol_types_run_stage_sets_timeout(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _load_script_module("generate_protocol_types", "scripts/generate_protocol_types.py")
    captured: dict[str, object] = {}

    def fake_run(command: list[str], *, check: bool, timeout: int) -> None:
        captured["command"] = command
        captured["check"] = check
        captured["timeout"] = timeout

    monkeypatch.setattr(module.subprocess, "run", fake_run)

    module.run_stage("example", ["echo", "ok"])

    assert captured == {
        "command": ["echo", "ok"],
        "check": True,
        "timeout": module.SUBPROCESS_TIMEOUT_SECONDS,
    }


def test_postprocess_types_applies_explicit_pipeline_passes() -> None:
    module = _load_script_module(
        "postprocess_protocol_types",
        "scripts/postprocess_protocol_types.py",
    )

    raw = """# generated by datamodel-codegen:\nclass EventMsg(RootModel[Foo | Bar]):\n    pass\nclass Record3Cstring2Cnever3E(BaseModel):\n    pass\nclass Example(RootModel[JsonValue]):\n    root: JsonValue\nitems: list[JsonValue]\nmapping: dict[str, JsonValue]\nEventMsg.model_rebuild()\nEventMsg.model_rebuild()\n"""

    processed, removed = module.postprocess_types(raw)

    assert "# ruff: noqa: F821" in processed
    assert "# mypy: ignore-errors" not in processed
    assert "class EventMsg(RootModel):" in processed
    assert "class EmptyObject(BaseModel):" in processed
    assert "RootModel['JsonValue']" in processed
    assert "list['JsonValue']" in processed
    assert "dict[str, 'JsonValue']" in processed
    assert processed.count("EventMsg.model_rebuild()") == 1
    assert removed == 2


def test_postprocess_schema_titles_applies_schema_normalization_passes() -> None:
    module = _load_script_module(
        "postprocess_schema_titles",
        "scripts/postprocess_schema_titles.py",
    )

    schema = {
        "$defs": {
            "ServerNotification": {
                "oneOf": [
                    {
                        "properties": {
                            "method": {"const": "turn-completed"},
                            "duration": {"type": "string", "description": "elapsed"},
                            "output_tokens": {"type": "number"},
                            "nullableValue": {"oneOf": [{"type": "string"}, {"type": "null"}]},
                        },
                        "required": ["duration", "nullableValue"],
                    }
                ]
            },
            "RequestId": {"type": "number"},
            "ExecCommandEndEvent": {"properties": {"exit_code": {"type": "number"}}},
        }
    }

    changed, added = module.add_titles(schema)
    relaxed, relaxed_count = module.relax_required_for_nullables(schema)
    request_id_fixed = module.enforce_request_id_integer(schema)
    exit_code_fixed = module.enforce_exec_exit_code_integer(schema)
    integers_coerced = module.enforce_integer_fields(schema)
    durations_patched = module.enforce_duration_union(schema)

    hoisted = schema["$defs"]["ServerNotification_TurnCompleted"]

    assert module.camelize("turn-completed") == "TurnCompleted"
    assert changed is True
    assert added == 1
    assert schema["$defs"]["ServerNotification"]["oneOf"] == [
        {"$ref": "#/$defs/ServerNotification_TurnCompleted"}
    ]
    assert hoisted["title"] == "ServerNotification_TurnCompleted"
    assert relaxed is True
    assert relaxed_count == 1
    assert hoisted["required"] == ["duration"]
    assert request_id_fixed is True
    assert schema["$defs"]["RequestId"]["type"] == ["string", "integer"]
    assert exit_code_fixed is True
    assert schema["$defs"]["ExecCommandEndEvent"]["properties"]["exit_code"]["type"] == "integer"
    assert integers_coerced == 1
    assert hoisted["properties"]["output_tokens"]["type"] == "integer"
    assert durations_patched == 1
    assert hoisted["properties"]["duration"]["oneOf"][0]["type"] == "string"
    assert hoisted["properties"]["duration"]["oneOf"][1]["properties"]["secs"]["type"] == "integer"
