#!/usr/bin/env python3
"""Apply the named post-generation passes for protocol type cleanup.

Pipeline contract:
1. Repair recursive forward references emitted by datamodel-code-generator.
2. Normalize union RootModel wrappers that would fail at class creation time.
3. Ensure generated-file directives are present.
4. Rename known unreadable generated aliases.
5. Append required model_rebuild() calls for wrapper unions.
6. Deduplicate rebuild calls from repeated runs.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from codex._file_utils import atomic_write_text

DEFAULT_PROTOCOL_TYPES_PATH = Path("codex/protocol/types.py")
UNION_WRAPPER_NAMES = (
    "EventMsg",
    "ClientRequest",
    "ServerRequest",
    "ServerNotification",
    "InputItem",
)
RENAME_MAP = {
    "Record3Cstring2Cnever3E": "EmptyObject",
}


@dataclass(frozen=True)
class TransformPass:
    name: str
    transform: Callable[[str], str]


def rewrite_recursive_jsonvalue_forward_refs(text: str) -> str:
    text = re.sub(r"RootModel\[([^\]]*?)JsonValue([^\]]*?)\]", r"RootModel[\1'JsonValue'\2]", text)
    text = re.sub(r"list\[JsonValue\]", "list['JsonValue']", text)
    text = re.sub(r"dict\[str, JsonValue\]", "dict[str, 'JsonValue']", text)
    return text.replace("''JsonValue''", "'JsonValue'")


def normalize_union_rootmodel_wrappers(text: str) -> str:
    text = re.sub(
        r"class\s+(EventMsg|ClientRequest|ServerRequest|ServerNotification|InputItem)\s*\(\s*RootModel\[[^\]]+\]\s*\):",
        lambda match: f"class {match.group(1)}(RootModel):",
        text,
    )
    return re.sub(
        r"'((?:EventMsg|ClientRequest|ServerRequest|ServerNotification|InputItem)[A-Za-z0-9_]+)'",
        r"\1",
        text,
    )


def ensure_generated_file_directives(text: str) -> str:
    lines = text.splitlines()
    directive_insert_at = 1
    for idx, line in enumerate(lines[:10]):
        if line.startswith("# generated by"):
            directive_insert_at = idx + 1
            break

    if "from __future__ import annotations" not in lines[:10]:
        lines.insert(directive_insert_at, "from __future__ import annotations")
        directive_insert_at += 1
    if "# ruff: noqa: F821" not in lines[:8]:
        lines.insert(directive_insert_at, "# ruff: noqa: F821")

    return "\n".join(lines) + ("\n" if text.endswith("\n") else "")


def rename_generated_aliases(text: str) -> str:
    for old, new in RENAME_MAP.items():
        text = re.sub(rf"\b{old}\b", new, text)
    return text


def append_union_wrapper_rebuilds(text: str) -> str:
    trailer: list[str] = []
    for name in UNION_WRAPPER_NAMES:
        if re.search(rf"^class\s+{name}\(\s*RootModel\s*\):", text, flags=re.M):
            trailer.append(f"{name}.model_rebuild()")
    if not trailer:
        return text
    return text.rstrip() + "\n\n" + "\n".join(trailer) + "\n"


def deduplicate_model_rebuild_calls(text: str) -> tuple[str, int]:
    seen: set[str] = set()
    deduped_lines: list[str] = []
    removed = 0

    for line in text.splitlines():
        match = re.match(r"^(\w+)\.model_rebuild\(\)\s*$", line)
        if match is None:
            deduped_lines.append(line)
            continue
        name = match.group(1)
        if name in seen:
            removed += 1
            continue
        seen.add(name)
        deduped_lines.append(line)

    return "\n".join(deduped_lines) + ("\n" if text.endswith("\n") else ""), removed


POSTPROCESS_PASSES = (
    TransformPass(
        "rewrite recursive JsonValue forward refs", rewrite_recursive_jsonvalue_forward_refs
    ),
    TransformPass("normalize union RootModel wrappers", normalize_union_rootmodel_wrappers),
    TransformPass("ensure generated file directives", ensure_generated_file_directives),
    TransformPass("rename unreadable generated aliases", rename_generated_aliases),
    TransformPass("append wrapper model_rebuild calls", append_union_wrapper_rebuilds),
)


def postprocess_types(text: str) -> tuple[str, int]:
    for transform_pass in POSTPROCESS_PASSES:
        text = transform_pass.transform(text)
    return deduplicate_model_rebuild_calls(text)


def main() -> int:
    path = DEFAULT_PROTOCOL_TYPES_PATH
    original_text = path.read_text()
    updated_text, removed_rebuilds = postprocess_types(original_text)
    atomic_write_text(path, updated_text)

    pass_names = ", ".join(transform_pass.name for transform_pass in POSTPROCESS_PASSES)
    if removed_rebuilds:
        print(
            "Types postprocess: ran passes "
            f"[{pass_names}] and removed {removed_rebuilds} duplicate model_rebuild() lines"
        )
    else:
        print(f"Types postprocess: ran passes [{pass_names}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
