name: Draft Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write

concurrency:
  group: draft-release
  cancel-in-progress: true

jobs:
  draft:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or update draft release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: next
          name: Unreleased (auto-updated)
          draft: true
          allow_updates: true
          generate_release_notes: true
          make_latest: false
          fail_on_unmatched_files: false
